-- AlterTable
ALTER TABLE `import_jobs` ADD COLUMN `error` TEXT NULL,
    ADD COLUMN `errorRows` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `existingRows` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `finishedAt` DATETIME(3) NULL,
    ADD COLUMN `outcomes` JSON NULL,
    ADD COLUMN `processed` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `readyRows` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `rows` JSON NULL,
    ADD COLUMN `updateExisting` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `updated` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `whatsappConfirmed` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `status` ENUM('PENDING', 'PROCESSING', 'DONE', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';
